version: '3.8'
services:
  redis:
    image: redis:8.2.0
    container_name: redis_v8.2.0
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - G:\docker\redis\data:/data  # 持久化数据目录
    command: redis-server --appendonly yes --appendfsync everysec  # 直接传递Redis配置参数